### PR TITLE
Catch IllegalArgumentException when external storage directory doesn't exist

### PR DESCRIPTION
**Pull request by RalfNieuwenhuizen**
Thank you for making a pull request ! Just a gentle reminder :)

1. If the PR is offering a feature please make the request to our "Feature Branch" 0.11.0
2. Bug fix request to "Bug Fix Branch" 0.10.9
3. Correct README.md can directly to master

### CODE REVIEW

**Comment by RalfNieuwenhuizen** [comment]
@lll000111 do you feel like merging this? I guess it won't harm anything. Tested and running since november.

**Comment by lll000111** [comment]
@RalfNieuwenhuizen See the README. I could merge _some_ PRs (but not even my own! They still need a review from the actual owner!) I don't want to be responsible for anything. I'm not the owner and I cannot replace him. I was made "Collaborator" because at the time I submitted a few patches before I could say "No". I don't even do mobile development! I was willing to help out but only with filesystem related stuff that I needed myself. I can't be the maintainer around here. Somebody has to folk the repo and become the new maintainer. I'm not going top merge something I cannot even test, the original owner has another repo with a test infrastructure. **I don't even own a "smart phone**, that's how badly positioned I am for this project!

**Comment by lll000111** [comment]
Ah I see, about my last sentence, PRs should not be for `master` but for the 0.10.9 branch in any case, so even if I would do maintenance on this project I would have to reject it :-(

**Comment by RalfNieuwenhuizen** [comment]
Thanks for your explanation. I'll be patient.

**Comment by lll000111** [comment]
FYI

react-native-fetch-blob has a new maintained location. [Check out the README.](https://github.com/wkh237/react-native-fetch-blob/blob/master/README.md)

Please consider submitting your PR there, this repository is unmaintained.

NOTE: Patches should be against the current development branch, not against `master`.

**Pull request closed without merging**
