### PR TITLE
Android Feature: Handle Arbitrary Providers

### PR DESCRIPTION
**Pull request by jsm**
Currently when trying to derive a real path from a URI in android, it will return null for third-party content providers (Ex: Google Drive, Dropbox).

To get a realPath, this downloads the file in the application's temporary directory, and returns the temporary file path.

I'm guessing I put this in a weird place, since Utils probably shouldn't be doing any network calls, but I wasn't sure how best to handle it, or if this library should even be handling it.

Thoughts?

### CODE REVIEW

**Comment by wkh237** [comment]
@jsm , it's okay. Thanks for the PR, I'll also cherry-pick this commit from branch `0.10.6` 👍

**Comment by jsm** [comment]
Sweet, thanks! Any ETA on an npm release of either 0.10.6 or 0.11.0?

**Comment by wkh237** [comment]
@jsm, I'm afraid there's no ETA on npm release 😢

**Comment by CptMaumau** [comment]
Hi, any ETA on 0.11.0 release? Really need this fix to have Google Drive working on my app.

**Comment by wkh237** [comment]
This has already been cherry-picked into 0.10.x.

**Pull request merged**
