### PR TITLE
Update RNFetchBlobNetwork.m

### PR DESCRIPTION
**Pull request by kejinliang**
Thank you for making a pull request ! Just a gentle reminder :)

1. If the PR is offering a feature please make the request to our "Feature Branch" 0.10.0
2. Bug fix request to "Bug Fix Branch" 0.9.6
3. Correct README.md can directly to master

### CODE REVIEW

**Comment by kejinliang** [comment]
This this the first time.

**Comment by wkh237** [comment]
@kejinliang , Thank you so much 🎉 I'll merge it and write some tests for it 😄

**Comment by wkh237** [comment]
refer to #141

**Comment by haibinyu** [comment]
Great！ But I wander if android has the same issue.

**Comment by kejinliang** [comment]
Hi, can you merge it on branch >=0.9.5. Thanks.

**Comment by kejinliang** [comment]
@wkh237  hi, when run npm install --save react-native-fetch-blob, it links version 0.9.5, but i want 0.9.6 to fix the problem. And when run npm install --save react-native-fetch-blob@0.9.6, it report error:
npm ERR! No compatible version found: react-native-fetch-blob@0.9.6
npm ERR! Valid install targets:
npm ERR! 0.9.5, 0.9.5-beta.4, 0.9.5-beta.3, 0.9.5-beta.2, 0.9.5-beta.1, 0.9.4, 0.9.4-beta.7, 0.9.4-beta.6, 0.9.4-beta.5, 0.9.4-beta.4, 0.9.4-beta.3, 0.9.4-beta.2, 0.9.4-beta.1, 0.9.3, 0.9.2, 0.9.2-beta.6, 0.9.2-beta.5, 0.9.2-beta.4, 0.9.2-beta.3, 0.9.2-beta.2, 0.9.2-beta.1, 0.9.1, 0.9.0, 0.9.0-beta.5, 0.9.0-beta.4, 0.9.0-beta.3, 0.9.0-beta.2, 0.9.0-beta.1, 0.8.2, 0.8.1, 0.8.0, 0.8.0-alpha.6, 0.8.0-alpha.5, 0.8.0-alpha.4, 0.7.5, 0.7.5-dev.1, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.7.0-dev.2, 0.7.0-dev.1, 0.6.4, 0.6.3, 0.6.3-dev.1, 0.6.2, 0.6.1, 0.6.0, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, 0.2.1
I need your help, thank you!

**Comment by wkh237** [comment]
@haibinyu , I've published a `beta` release to npm, please try upgrade you package.

In this version, you are able to append response data to existing file by append `?append=true` to the file path 

```js
RNFetchBlob.config({
  path : pathOfFile + '?append=true'
})
.fetch('GET', 'http://example.com')
```

Please try if it works, thank you 😄

**Pull request merged**
