### PR TITLE
0.10.9

### PR DESCRIPTION
**Pull request by lll000111**
I fixed a handful of issues from the list. Everything is for Android except for a very small change for `unlink` on iOS.

### CODE REVIEW

**Comment by lll000111** [comment]
@dantman So I pushed this too: https://github.com/wkh237/react-native-fetch-blob/pull/510/commits/68ce5c43ea2d6c226e83d21ba9b5c7777f6fccba

**Comment by CptMaumau** [comment]
This seems to have important fixes for Android, could it be merged @wkh237 ?

**Comment by Jacse** [comment]
@lll000111 any chance you could merge this? I know @wkh237 is inactive, could you take over or maintain a fork?

**Comment by lll000111** [comment]
I can't merge because I don't have a full environment (and no iOS at all), no time, I only care(d) about the filesystem access to begin with (and only on Android). Sorry! But what prevents you from forking the repo and applying the patch? Just for yourself, doesn't even have to happen on Github.

**Comment by Jacse** [comment]
@lll000111 thanks for the quick reply! Completely understandable. That's probably what I'll end up doing, I was just hoping to see the library maintained.

**Comment by lll000111** [comment]
@Jacse Given the many PRs that have accumulated I thought my call for a maintainer at the top of the `README.md` would yield more responses than none...

**Comment by jdmunro** [comment]
@lll000111 I don't mind giving a hand with the iOS maintenance

**Comment by lll000111** [comment]
@jdmunro Thanks, but I'm not maintaining anything, I became a "Collaborator" by accident, I just submitted lots of patches at some point, for stuff that I needed... The package needs to be forked and owned by somebody new, completely. All I can do is add a link to the README, I have no admin rights here.

**Comment by jdmunro** [comment]
@lll000111 Understood

**Review by G-2-Z — CHANGES_REQUESTED** [review]
missing ' at [RNFetchBlobWriteStream.js:66](https://github.com/wkh237/react-native-fetch-blob/pull/510/commits/6802def609e1f7f357f733c9e08350fe42816b8c#diff-a8efea81e990ab14c76e5b24c7399bfaR66)

**Pull request closed without merging**
