### PR TITLE
fix syntaxerror

### PR DESCRIPTION
**Pull request by royxue**
Hi, when I use this module, found this bug, so make a PR to fix it ;)

```
SyntaxError: ./node_modules/react-native-fetch-blob/polyfill/Blob.js: Unterminated string constant (289:28)
  287 |   safeClose() {
  288 |     if(this._closed)
> 289 |       return Promise.reject('Blob has been released.)
      |                             ^
  290 |     this._closed = true
  291 |     if(!this._isReference) {
  292 |       return fs.unlink(this._ref).catch((err) => {
```

Thank you for making a pull request ! Just a gentle reminder :)

1. If the PR is offering a feature please make the request to our "Feature Branch" 0.11.0
2. Bug fix request to "Bug Fix Branch" 0.10.8
3. Correct README.md can directly to master

### CODE REVIEW

**Comment by alinz** [comment]
@wkh237 can you merge this. This is major issue which prevents the library to function.

**Comment by borisyankov** [comment]
Yes, the library is currently broken. Merge plus publish is needed.

**Comment by wkh237** [comment]
This should have been fixed in `0.10.8` have you upgrade your package ?

**Comment by royxue** [comment]
I think this was resolved in `0.10.8`, so closed ;)

**Pull request closed without merging**
