### PR TITLE
Fix Crash In React Native 0.50 & 0.51

### PR DESCRIPTION
**Pull request by huhuanming**
solved `cannot find  self` temporarily by this way and will open a PR in oboe lately.

### CODE REVIEW

**Comment by Freddy03h** [comment]
This change doesn't fix the issue in my projet (RN 0.50.1, after deleted node_modules, re-yarn and XCode > Product > Clean)

It seems that `global` and `window` are the same object on Debug Mode, and we still go to the catch on Release Mode.

**Comment by huhuanming** [comment]
But work well in my project...

it seems that your project includes other issues, not only this.

**Comment by Freddy03h** [comment]
Hum, weird…

What's you config ?

Mine: 
- macOS 10.13.1
- XCode 9.1
- iOS 11.1 (simulator and real device)
- node 8.7.0
- yarn 1.2.1

**Comment by huhuanming** [comment]
Me too, my config is same as your.

**Comment by aforty** [comment]
@Freddy03h Try Your running `watchman watch-del-all && rm -rf $TMPDIR/react-*` and `react-native start --reset-cache`.

This branch works for me.

**Comment by Freddy03h** [comment]
@aforty I tried it, I also tried after updating node (9.1.0) and yarn (1.3.2), I also restart my computer…

But i still get the same issue on Release Mode : `Got JS Exception: Can't find variable: window ( … main.jsbundle:534)` on XCode, with @huhuanming fork
This issue is also described by @bnjm : https://github.com/wkh237/react-native-fetch-blob/issues/588#issuecomment-342272145

No problem to build on Debug Mode, but the `main.jsbundle` for the Release version emits this error at runtime.

**Comment by huhuanming** [comment]
check your `yarn.lock` and find `react-native-fetch-blob`

image

**Comment by bnjm** [comment]
@Freddy03h I released my `window` issue is actually coming from another module that includes a polyfill. 

Seems like there are a number of release-only bugs relating to globals, which suggests an issue with the bundler. See here:  

https://github.com/GeekyAnts/NativeBase/issues/1348#issuecomment-342757700

**Comment by Freddy03h** [comment]
@bnjm Oh yes I just find that the JS Exception `Can't find variable: window` is emitted by an other module.

Thank you all !

**Comment by aforty** [comment]
The bundler definitely has an issue in 0.50.x. I discovered another Android-only issue where `Promise` is not defined. I downgraded to 0.49.5 for now.

**Comment by aforty** [comment]
FYI, react-native@0.50.3 fixes this bundler issue.

**Comment by Freddy03h** [comment]
I'm still stuck with the same issue described here : https://github.com/GeekyAnts/NativeBase/issues/1348 (but I don't use NativeBase)

Anyways, It's no more related to `react-native-fetch-blob`.

**Comment by huhuanming** [comment]
@Freddy03h Freddy

Check your `yarn.lock`， maybe you can Found the parent of NativeBase.

**Comment by huhuanming** [comment]
It was fix in React Native 0.50.3, I will close this PR now.

**Pull request closed without merging**
