### PR TITLE
Add podspec

### PR DESCRIPTION
**Pull request by adbl**
It's all in the title!

### CODE REVIEW

**Comment by adbl** [comment]
@wkh237 uhm, the directory structure has me a bit confused, should the podspec file go under `src/` ? It needs to be included in the npm package...

**Comment by wkh237** [comment]
Hi @adbl , thanks for the PR 👍 Yes, the `src` folder is where the npm package located, all files in `src` will be downloaded to `node_modules/react-native-fetch-blob` when npm install 😄

**Comment by adbl** [comment]
@wkh237 cool, fixed!

**Comment by wkh237** [comment]
@adbl really appreciate your great work 👍

**Comment by adbl** [comment]
Thanks! 😊

**Comment by adbl** [comment]
@wkh237 I noticed you included the README part in 0.9.4 beta2 tag, but I don't see the podspec file there (it's still in master)?

**Comment by wkh237** [comment]
I forgot to merge master before publish 0.9.4-beta.2 ! 😲  I will do it in next beta release !

**Pull request merged**
