### PR TITLE
fix redefine

### PR DESCRIPTION
**Pull request by asmh1989**

### CODE REVIEW

**Comment by wkh237** [comment]
@asmh1989 , could you provide information about what is the PR for and the problem it resolves?

**Comment by asmh1989** [comment]
```
RNFetchBlob.fetch('GET', url,headers)
```
I put correct `If-modified-since` in `headers`,  servers not return 304 code, it return 200
After this modify, it return correct. 
I think `defaultConfigObject `,   Should not be `nil`,  to set into `NSURLSession`

**Comment by lll000111** [comment]
This PR is no longer necessary, the issue that was in the code at that time, see (beginning of June)

https://github.com/wkh237/react-native-fetch-blob/blob/869bb47d161ae17f4d7611c9ff57ee36446f1bf2/ios/RNFetchBlobNetwork.m#L194

is no longer there, see (beginning of September)

https://github.com/wkh237/react-native-fetch-blob/blob/821eeb0f9db1736009ee791c14298ef72144a825/ios/RNFetchBlobNetwork.m#L197

**Comment by marlti7** [comment]
in android , The problem still exists.

**Comment by lll000111** [comment]
@marlti7 This PR changes a single file in the ios subdirectory. I have no idea what you are writing about....

**Pull request closed without merging**
